### Geant4 Physics list, in this case https://geant4.web.cern.ch/documentation/dev/plg_html/PhysicsListGuide/reference_PL/QGSP_BERT.html
/GsimPhysicsListFactory/QGSP_BERT/buildAndRegister

### Particle gun (GeneralParticleSource)
/GsimPrimaryGeneratorActionFactory/GsimGeneralParticleSource/buildAndRegister gps
/gps/particle kaon0L
/gps/energy 1 GeV
/gps/position 0 0 -1 m
/gps/direction 0 0 1

### Particle spectrum. It modifies vertex and momentum of the particle gun.
/GsimSpectrumFactory/GsimE14Step2HNPointSpectrum/buildAndRegister
/GsimSpectrum/GsimE14Step2HNPointSpectrum/addSpectrum Special
/GsimSpectrum/GsimE14Step2HNPointSpectrum/setParameter 15*cm

### Visualisation
/control/execute oglsini.mac #edit this to change visualisation mode (in window or in file)
#/GsimEventAction/setVisualizationMode 1 #uncomment this and next line for in-window visualisation
#/GsimEventAction/setAccumulationNumber 1 #number of events overplayed in some event display.
/GsimTrackingAction/setBriefTrackStore true

/GsimPhysicsList/addPhaseSpaceDecay kaon0L pi0  e+ e-

/GsimDetector/world/setParameters 5*m 5*m 60*m
/GsimDetector/world/setOuterVisibility 0
/GsimDetectorFactory/GsimDetector/buildAndRegister e14 /world

/control/execute /group/had/koto2/mdgalati/step2geom15cm.mac

/GsimDetector/world/e14/setThisAndDaughterMtimeStore true
/GsimEventAction/setSkipEmptyData true



/GsimDetector/world/setThisUserTimeMax 1000 ns

/GsimDetector/world/e14/setFastSimulationLevel 5
/GsimDetector/world/e14/setThisAndDaughterHitsStore true

/GsimDetectorManager/update
/run/initialize
#/run/beamOn 20
